/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tavant_mobilecoe_treasurehunt_camera_ComapareImage */

#ifndef _Included_com_tavant_mobilecoe_treasurehunt_camera_ComapareImage
#define _Included_com_tavant_mobilecoe_treasurehunt_camera_ComapareImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tavant_mobilecoe_treasurehunt_camera_ComapareImage
 * Method:    compareImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_tavant_mobilecoe_treasurehunt_camera_ComapareImage_compareImage
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
